### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by zenorocha** [siqueirabt/b4x-theme-dracula#1]
Hey @siqueirabt, I couldn't identify what language B4X supports, but would you be able to create an equivalent code snippet and take a new screenshot?

See https://github.com/dracula/dracula-theme/discussions/444 for more information.

**Comment by lucassiqueirago** [comment]
Hello, b4x is a proprietary development language created by AnywhereSoftware, which is very similar to visual basic.

I'm updating the screenshot

**Comment by zenorocha** [comment]
Awesome @siqueirabt! Would you mind posting that code snippet here too? https://github.com/dracula/dracula-theme/discussions/444 Thanks!
